### ISSUE TITLE
sys-libs/ncurses-5.9-r101:5 build fails

### ISSUE THREAD

**Issue by MageSlayer** [MageSlayer/paludis-gentoo-patches#13]
> I have been having problems with sys-libs/ncurses-5.9-r101:5 for a while now, but worked around it by 
> simply skipping the installation. The relevant bug is actually ancient and fixed with portage. (Cf. #545532)
> The fix for that particular bug relied on the CONFIG_SHELL environment variable in the ncurses ebuild. 
> This seems to get lost during the call to econf.

Originally created in #12

**Comment by MageSlayer** [comment]
@bodograumann
I've installed ncurses-5.9-r101 just fine using latest eapi7 branch.
Could you provide some details?

**Comment by bodograumann** [comment]
I have `/bin/sh -> /bin/dash`. The bug #545532 had to do with some build scripts requiring bash I think. So maybe you have bash as your default system shell?

**Comment by MageSlayer** [comment]
Yes, I have bash.
I guess it's default Gentoo configuration.

Should be fixed now.
Please test.

**Comment by bodograumann** [comment]
That did the trick. Thank you.
