### ISSUE TITLE
tensorflow-1.13.1 ebuild causing dependency issues

### ISSUE THREAD

**Issue by hlandgarten** [MageSlayer/paludis-gentoo-patches#18]
The latest tensorflow-1.13.1 ebuild causes the following illogical blockages on cudnn.
cudnn-7.4.2.24 as well as nvidia-cuda-toolkit-10.0.130 are installed. This combination should be allowed by the tensorflow ebuild.

!   dev-libs/cudnn
    Reasons: target (installed-packages::installed), restarted because of sci-libs/tensorflow-1.13.1:0::installed, sci-libs/tensorflow-1.13.1:0::installed
    Unsuitable candidates:
      * dev-libs/cudnn-6.0:0::gentoo
        Did not meet =dev-libs/cudnn-7.0*, use existing if same, installing to / from sci-libs/tensorflow-1.13.1:0::installed
        Did not meet =dev-libs/cudnn-7.1*, use existing if same, installing to / from sci-libs/tensorflow-1.13.1:0::installed
        Did not meet =dev-libs/cudnn-7.4*, use existing if same, installing to / from restarted because of sci-libs/tensorflow-1.13.1:0::installed (and 1 more)
      * dev-libs/cudnn-7.0.5-r1:0::gentoo
        Did not meet =dev-libs/cudnn-7.1*, use existing if same, installing to / from sci-libs/tensorflow-1.13.1:0::installed
        Did not meet =dev-libs/cudnn-7.4*, use existing if same, installing to / from restarted because of sci-libs/tensorflow-1.13.1:0::installed (and 1 more)
      * dev-libs/cudnn-7.1.4:0::gentoo
        Did not meet =dev-libs/cudnn-7.0*, use existing if same, installing to / from sci-libs/tensorflow-1.13.1:0::installed
        Did not meet =dev-libs/cudnn-7.4*, use existing if same, installing to / from restarted because of sci-libs/tensorflow-1.13.1:0::installed (and 1 more)
      * dev-libs/cudnn-7.4.1.5:0::gentoo
        Did not meet =dev-libs/cudnn-7.0*, use existing if same, installing to / from sci-libs/tensorflow-1.13.1:0::installed
        Did not meet =dev-libs/cudnn-7.1*, use existing if same, installing to / from sci-libs/tensorflow-1.13.1:0::installed
      * dev-libs/cudnn-7.4.2.24:0::gentoo
        Did not meet =dev-libs/cudnn-7.0*, use existing if same, installing to / from sci-libs/tensorflow-1.13.1:0::installed
        Did not meet =dev-libs/cudnn-7.1*, use existing if same, installing to / from sci-libs/tensorflow-1.13.1:0::installed
      * dev-libs/cudnn-7.5.0.56:0::gentoo
        Did not meet =dev-libs/cudnn-7.0*, use existing if same, installing to / from sci-libs/tensorflow-1.13.1:0::installed
        Did not meet =dev-libs/cudnn-7.1*, use existing if same, installing to / from sci-libs/tensorflow-1.13.1:0::installed
        Did not meet =dev-libs/cudnn-7.4*, use existing if same, installing to / from restarted because of sci-libs/tensorflow-1.13.1:0::installed (and 1 more)

**Comment by kdudka** [comment]
`sci-libs/tensorflow-1.13.1:0::installed` is the thing you have already installed, not the one that can be installed from available repositories.  Those two things may have different dependencies.  Try to append `sci-libs/tensorflow` on the `cave resolve` command line.

**Comment by hlandgarten** [comment]
I reinstalled tensorflow with the latest ebuild 2 days ago. After that this isssue started.

**Comment by hlandgarten** [comment]
same issue with:
cave resolve cudnn tensorflow -cx -Cs

**Comment by hlandgarten** [comment]
This is the part of the ebuild that appears to be causing the issue:
        cuda? (
                || (
                        ( =dev-util/nvidia-cuda-toolkit-10.0*[profiler] =dev-libs/cudnn-7.4* )
                        ( =dev-util/nvidia-cuda-toolkit-9.2*[profiler] =dev-libs/cudnn-7.1* )
                        ( =dev-util/nvidia-cuda-toolkit-9.1*[profiler] =dev-libs/cudnn-7.0* )
                )
        )
Notice that when errors are reported for cudnn-7.4.2.24 the condition that is satified in not reported in the error report but an erroneous error is reported:

* dev-libs/cudnn-7.4.2.24:0::gentoo
Did not meet =dev-libs/cudnn-7.0*, use existing if same, installing to / from sci-libs/tensorflow-1.13.1:0::installed
Did not meet =dev-libs/cudnn-7.1*, use existing if same, installing to / from sci-libs/tensorflow-1.13.1:0::installed

**Comment by MageSlayer** [comment]
Could not reproduce using current Portage tree:
```
# cave resolve --lazy tensorflow dev-cpp/libjson-rpc-cpp --permit-old-version '*/*'

... skipped...

-n  dev-util/nvidia-cuda-toolkit:0::gentoo (not the best version) 10.0.130 to ::installed
    "NVIDIA CUDA Toolkit (compiler and friends)"
    -debugger -doc -eclipse profiler build_options: symbols=strip -dwarf_compress -optional_tests -trace work=tidyup
    Reasons: dev-libs/cudnn-7.4.2.24:0::gentoo, sci-libs/tensorflow-1.13.1:0::gentoo
    1.88 GBytes to download

-n  dev-libs/cudnn:0::gentoo (not the best version) 7.4.2.24 to ::installed
    "NVIDIA Accelerated Deep Learning on GPU library"
    build_options: symbols=strip -dwarf_compress -optional_tests -trace work=tidyup
    Reasons: sci-libs/tensorflow-1.13.1:0::gentoo
    404.82 MBytes to download

n   sci-libs/tensorflow:0::gentoo 1.13.1 to ::installed
    "Computation framework using data flow graphs for scalable machine learning"
    cuda -mpi python CPU_FLAGS_X86: avx avx2 fma3 -fma4 sse sse2 sse3 sse4_1 sse4_2 PYTHON_TARGETS: python2_7 -python3_5 python3_6 -python3_7 build_options: symbols=strip -dwarf_compress -optional_tests -trace work=tidyup
    Reasons: target, sci-libs/tensorflow-estimator-1.13.0:0::gentoo, sci-visualization/tensorboard-1.13.1:0::gentoo
    43.91 MBytes to download

n   sci-libs/tensorflow-estimator:0::gentoo 1.13.0 to ::installed
    "A high-level TensorFlow API that greatly simplifies machine learning programming"
    PYTHON_TARGETS: python2_7 -python3_5 python3_6 -python3_7 build_options: symbols=strip -dwarf_compress -optional_tests -trace work=tidyup
    Reasons: sci-libs/tensorflow-1.13.1:0::gentoo
    518.43 kBytes to download

```
I guess if you think it's problem in Paludis - a much smaller synthetic ebuild graph is necessary.

**Comment by hlandgarten** [comment]
Take out the -z and try it.  I have the issue on every cave resolve world -c

**Comment by MageSlayer** [comment]
Same story without -z.

**Comment by hlandgarten** [comment]
Please try with -c.

**Comment by MageSlayer** [comment]
A lot of extra stuff, but still builds graph fine.

**Comment by hlandgarten** [comment]
I have to try to delete the 4 packages and install fresh. Tensorflow is a long compile. Hopefully, that will fix the issue. Thanks for the help.

Harris Landgarten
Deep Learning Technology Inc.
516-299-8390

----- Original Message -----
