### ISSUE TITLE
paludis will not build with boost-1.70.0

### ISSUE THREAD

**Issue by hlandgarten** [MageSlayer/paludis-gentoo-patches#20]
it fails during configure

**Comment by MageSlayer** [comment]
Could you check latest paludis?

**Comment by hlandgarten** [comment]
Have there been changes?

**Comment by MageSlayer** [comment]
Yes, I've just pushed changes to master and eap7 branch.

**Comment by hlandgarten** [comment]
Great. I will test later today.

Harris Landgarten
Deep Learning Technology Inc.
516-299-8390

----- Original Message -----

**Comment by MageSlayer** [comment]
@hlandgarten 
Any news on that?

**Comment by hlandgarten** [comment]
fixed by last update. Thanks.
