### ISSUE TITLE
new changes to /etc/portage/profile/make.profile break paludis

### ISSUE THREAD

**Issue by hlandgarten** [MageSlayer/paludis-gentoo-patches#21]
# Hans de Graaff <graaff@gentoo.org) (2019-07-17)
# Temporary RUBY_TARGETS for bug 688976
RUBY_TARGETS="ruby24 -ruby25"

completely breaks paludis

**Comment by MageSlayer** [comment]
Do you mean ruby-2.5 break paludis build?

**Comment by hlandgarten** [comment]
world-up
Resolving: 


Error:
  * In program cave resolve --resume-file /tmp/resume_file -c -km -Km -Cs -P */* -Si -Rn installed-packages:
  * When adding targets from commandline:
  * When parsing user package dep spec 'installed-packages':
  * When parsing generic package dep spec 'installed-packages':
  * When loading profiles '/usr/portage/profiles/default/linux/amd64/17.0/desktop/gnome/systemd' for repository 'gentoo':
  * When adding USE_EXPAND to USE:
  * Name '-ruby25' is not a valid unprefixed choice name (paludis::UnprefixedChoiceNameError)

**Comment by hlandgarten** [comment]
tail /usr/portage/profiles/arch/amd64/make.defaults 
IUSE_IMPLICIT="abi_x86_64"

# Andreas K. Hüttel <dilfridge@gentoo.org> (2017-06-02)
# Enable USE=libtirpc by default, to ease dependency resolution during
# the stabilization of glibc-2.26. Bug 657148
USE="libtirpc"

# Hans de Graaff <graaff@gentoo.org) (2019-07-17)
# Temporary RUBY_TARGETS for bug 688976
RUBY_TARGETS="ruby24 -ruby25"

The last line is causing paludis to not work

**Comment by MageSlayer** [comment]
Ok. I see now.
It's definitely a bug worth fixing.

**Comment by MageSlayer** [comment]
Should be fixed now.
Please test.

**Comment by hlandgarten** [comment]
Fixed

**Comment by MageSlayer** [comment]
Thanks.
I'll close it then.
