### ISSUE TITLE
Bash associative arrays (i.e., hashes) break paludis's loadsaveenv

### ISSUE THREAD

**Issue by Ionic** [MageSlayer/paludis-gentoo-patches#26]
Updating `net-misc/geoipupdate`, I ran into this issue:

```
/var/tmp/paludis/net-misc-geoipupdate-4.3.0/temp/loadsaveenv: line 458: github.com%2Fstretchr%2Fobjx%2F@v%2Fv0.1.0.zip: syntax error: invalid arithmetic operator (error token is ".com%2Fstretchr%2Fobjx%2F@v%2Fv0.1.0.zip")
```

and indeed, the file contains this:

```bash
_GOMODULE_GOSUM_REVERSE_MAP=([github.com%2Fstretchr%2Fobjx%2F@v%2Fv0.1.0.zip]="github.com/stretchr/objx/@v/v0.1.0.zip" [github.com%2Fspf13%2Fpflag%2F@v%2Fv1.0.5.mod]="github.com/spf13/pflag/@v/v1.0.5.mod" [github.com%2Fpmezard%2Fgo-difflib%2F@v%2Fv1.0.0.mod]="github.com/pmezard/go-difflib/@v/v1.0.0.mod" [github.com%2Fstretchr%2Fobjx%2F@v%2Fv0.1.0.mod]="github.com/stretchr/objx/@v/v0.1.0.mod" [github.com%2Fdavecgh%2Fgo-spew%2F@v%2Fv1.1.1.mod]="github.com/davecgh/go-spew/@v/v1.1.1.mod" [github.com%2Fkr%2Fpretty%2F@v%2Fv0.2.0.zip]="github.com/kr/pretty/@v/v0.2.0.zip" [github.com%2Fpmezard%2Fgo-difflib%2F@v%2Fv1.0.0.zip]="github.com/pmezard/go-difflib/@v/v1.0.0.zip" [github.com%2Fdavecgh%2Fgo-spew%2F@v%2Fv1.1.0.mod]="github.com/davecgh/go-spew/@v/v1.1.0.mod" [gopkg.in%2Fcheck.v1%2F@v%2Fv0.0.0-20161208181325-20d25e280405.mod]="gopkg.in/check.v1/@v/v0.0.0-20161208181325-20d25e280405.mod" [gopkg.in%2Fcheck.v1%2F@v%2Fv1.0.0-20190902080502-41f04d3bba15.zip]="gopkg.in/check.v1/@v/v1.0.0-20190902080502-41f04d3bba15.zip" [github.com%2Fstretchr%2Ftestify%2F@v%2Fv1.5.0.zip]="github.com/stretchr/testify/@v/v1.5.0.zip" [gopkg.in%2Fyaml.v2%2F@v%2Fv2.2.7.mod]="gopkg.in/yaml.v2/@v/v2.2.7.mod" [github.com%2Fkr%2Fpretty%2F@v%2Fv0.2.0.mod]="github.com/kr/pretty/@v/v0.2.0.mod" [github.com%2Fgofrs%2Fflock%2F@v%2Fv0.7.1.mod]="github.com/gofrs/flock/@v/v0.7.1.mod" [github.com%2Fkr%2Ftext%2F@v%2Fv0.1.0.zip]="github.com/kr/text/@v/v0.1.0.zip" [github.com%2Fmaxmind%2Fgeoipupdate%2F@v%2Fv4.0.2+incompatible.zip]="github.com/maxmind/geoipupdate/@v/v4.0.2+incompatible.zip" [github.com%2Fgofrs%2Fflock%2F@v%2Fv0.7.1.zip]="github.com/gofrs/flock/@v/v0.7.1.zip" [github.com%2Fstretchr%2Ftestify%2F@v%2Fv1.4.0.mod]="github.com/stretchr/testify/@v/v1.4.0.mod" [github.com%2Fdavecgh%2Fgo-spew%2F@v%2Fv1.1.1.zip]="github.com/davecgh/go-spew/@v/v1.1.1.zip" [github.com%2Fpkg%2Ferrors%2F@v%2Fv0.9.0.mod]="github.com/pkg/errors/@v/v0.9.0.mod" [github.com%2Fkr%2Ftext%2F@v%2Fv0.1.0.mod]="github.com/kr/text/@v/v0.1.0.mod" [github.com%2Fstretchr%2Ftestify%2F@v%2Fv1.4.0.zip]="github.com/stretchr/testify/@v/v1.4.0.zip" [github.com%2Fpkg%2Ferrors%2F@v%2Fv0.9.1.zip]="github.com/pkg/errors/@v/v0.9.1.zip" [gopkg.in%2Fyaml.v2%2F@v%2Fv2.2.7.zip]="gopkg.in/yaml.v2/@v/v2.2.7.zip" [gopkg.in%2Fcheck.v1%2F@v%2Fv1.0.0-20190902080502-41f04d3bba15.mod]="gopkg.in/check.v1/@v/v1.0.0-20190902080502-41f04d3bba15.mod" [github.com%2Fstretchr%2Ftestify%2F@v%2Fv1.5.1.zip]="github.com/stretchr/testify/@v/v1.5.1.zip" [github.com%2Fstretchr%2Ftestify%2F@v%2Fv1.5.0.mod]="github.com/stretchr/testify/@v/v1.5.0.mod" [gopkg.in%2Fyaml.v2%2F@v%2Fv2.2.2.zip]="gopkg.in/yaml.v2/@v/v2.2.2.zip" [github.com%2Fstretchr%2Ftestify%2F@v%2Fv1.5.1.mod]="github.com/stretchr/testify/@v/v1.5.1.mod" [github.com%2Fkr%2Fpty%2F@v%2Fv1.1.1.mod]="github.com/kr/pty/@v/v1.1.1.mod" [gopkg.in%2Fyaml.v2%2F@v%2Fv2.2.2.mod]="gopkg.in/yaml.v2/@v/v2.2.2.mod" [github.com%2Fpkg%2Ferrors%2F@v%2Fv0.9.1.mod]="github.com/pkg/errors/@v/v0.9.1.mod" [github.com%2Fspf13%2Fpflag%2F@v%2Fv1.0.5.zip]="github.com/spf13/pflag/@v/v1.0.5.zip" [github.com%2Fpkg%2Ferrors%2F@v%2Fv0.9.0.zip]="github.com/pkg/errors/@v/v0.9.0.zip" )
```

This comes from the `go-module` eclass:

```bash
# @ECLASS-VARIABLE: _GOMODULE_GOSUM_REVERSE_MAP
# @DESCRIPTION:
# Mapping back from Gentoo distfile name to upstream distfile path.
# Associative array to avoid O(N*M) performance when populating the GOPROXY
# directory structure.
declare -A -g _GOMODULE_GOSUM_REVERSE_MAP
```

So far, luckily, `go-module` is the only location using associative arrays, so the breakage is still pretty contained.

It's still a showstopper and I'm not sure how to fix this.

The main issue is that paludis uses `set` to dump out all variables (in [builtin_saveenv.bash for EAPI 0](https://github.com/MageSlayer/paludis-gentoo-patches/blob/eapi7/paludis/repositories/e/ebuild/0/builtin_saveenv.bash#L23), [builtin_saveenv.bash for exheres 0](https://github.com/MageSlayer/paludis-gentoo-patches/blob/eapi7/paludis/repositories/e/ebuild/exheres-0/builtin_saveenv.bash#L23) and [source_functions.bash](https://github.com/MageSlayer/paludis-gentoo-patches/blob/eapi7/paludis/repositories/e/ebuild/source_functions.bash#L54)), which works, but doesn't include extended attributes.

We should probably use `declare -p` instead to more correctly export the data.

I did run into some pretty big problem when doing so about three months ago, but I can't remember all specifics.

One issue was that the `loadsaveenv` file is loaded back in a shell function via `source`. `declare` and `typeset` typically make variables local to the function iff called in a function, so if we just load back the data returned by `declare -p`, everything will be gone once the function terminates.

To counter this, I mangled all `declare` calls to always include `-g` and insert the variables into global scope.

If I remember correctly, this created another set of problems. Mainly with read-only variables which can't be re-set. Filtering out read-only variables indefinitely would be a bad idea, though, for obvious reasons. One approach that works might be to filter out read-only variables if they are already set in global scope. Will have to test this some rainy day.

**Comment by Ionic** [comment]
FWIW, a fun workaround for this issue (currently) is to rewrite the `go-module` eclass so that it doesn't use associative arrays, which really isn't all that difficult:

```diff
--- go-module.eclass.orig	2020-09-17 09:29:31.687844294 +0200
+++ go-module.eclass	2020-09-17 09:33:18.007360418 +0200
@@ -147,7 +147,8 @@ EXPORT_FUNCTIONS src_unpack pkg_postinst
 # Mapping back from Gentoo distfile name to upstream distfile path.
 # Associative array to avoid O(N*M) performance when populating the GOPROXY
 # directory structure.
-declare -A -g _GOMODULE_GOSUM_REVERSE_MAP
+declare -a -g _GOMODULE_GOSUM_REVERSE_MAP_DIST
+declare -a -g _GOMODULE_GOSUM_REVERSE_MAP_REL
 
 # @FUNCTION: go-module_set_globals
 # @DESCRIPTION:
@@ -215,7 +216,8 @@ go-module_set_globals() {
 			_distfile="${_reluri//\//%2F}"
 
 			EGO_SUM_SRC_URI+=" ${_uri} -> ${_distfile}${newline}"
-			_GOMODULE_GOSUM_REVERSE_MAP["${_distfile}"]="${_reluri}"
+			_GOMODULE_GOSUM_REVERSE_MAP_DIST+=( "${_distfile}" )
+			_GOMODULE_GOSUM_REVERSE_MAP_REL+=( "${_reluri}" )
 		done
 	done
 
@@ -230,7 +232,8 @@ go-module_set_globals() {
 	# Ensure these variables are not changed past this point
 	readonly EGO_SUM
 	readonly EGO_SUM_SRC_URI
-	readonly _GOMODULE_GOSUM_REVERSE_MAP
+	readonly _GOMODULE_GOSUM_REVERSE_MAP_DIST
+	readonly _GOMODULE_GOSUM_REVERSE_MAP_REL
 
 	# Set the guard that we are safe
 	_GO_MODULE_SET_GLOBALS_CALLED=1
@@ -276,7 +279,13 @@ _go-module_src_unpack_gosum() {
 	local f
 	local goproxy_mod_dir
 	for f in ${A}; do
-		goproxy_mod_path="${_GOMODULE_GOSUM_REVERSE_MAP["${f}"]}"
+		local idx='-1'
+		local i='0'
+		local goproxy_mod_path=''
+		for (( i = 0; i < ${#_GOMODULE_GOSUM_REVERSE_MAP_DIST[@]}; ++i )); do
+			[[ "${_GOMODULE_GOSUM_REVERSE_MAP_DIST[${i}]}" == "${f}" ]] && idx="${i}" && break
+		done
+		[[ "${idx}" != '-1' ]] && goproxy_mod_path="${_GOMODULE_GOSUM_REVERSE_MAP_REL[${idx}]}"
 		if [[ -n "${goproxy_mod_path}" ]]; then
 			debug-print-function "Populating go proxy for ${goproxy_mod_path}"
 			# Build symlink hierarchy
```

Still, paludis needs proper support for these sort of things.

**Comment by MageSlayer** [comment]
Yes, sure. Paludis should support all ebuild features.

But to summarize, are you trying to state that Paludis exports/prints associative arrays to text incorrectly now?
As I understand, it's internal Bash expression that does that, right? Doesn't portage does the same?

**Comment by Ionic** [comment]
> But to summarize, are you trying to state that Paludis exports/prints associative arrays to text incorrectly now?

Well... illegal to bash, at least.

To dive a bit more into details: both package managers save a set of metadata for packages in `/var/db/pkg/${CATEGORY}/${PF}/`. This includes its ebuild and a file commonly called `environment.bz2`, which contains a dump of all variables and functions at the time the ebuild was processed. This is necessary because things change, but you still want to retain the behavior a package had when it was written when uninstalling an older version.

Paludis and portage generate this file differently, with paludis being "incorrect".

For instance, the `enviroment.bz2` file for gcc:8.4.0 starts like this when installed with portage:

```
declare -x A="gcc-8.4.0.tar.xz gcc-8.4.0-patches-2.tar.bz2"
declare -x ABI="amd64"
declare -x ABI_MIPS=""
declare -x ABI_PPC=""
```

while the `environment.bz2` file for gcc:9.3.0 (yes, different version, but I have two packages built with different package managers handy, so I'll use this as an example) starts like this when installed with paludis:

```
A='gcc-9.3.0.tar.xz gcc-9.3.0-patches-4.tar.bz2'
ABI=amd64
ABI_MIPS=
ABI_PPC=
```

Paludis uses the `set` builtin to dump the variables (and a small internal program called print-exports that just dumps all exported variables), while portage uses `declare -p` (I guess, haven't actually checked but probably should).

For most things, that works well enough.

For instance, bash can automatically determine whether a variable is a simple string or an array:

```bash
arr=("this" "is" "an" "array")
simp="this is a simple string"
```

Integer-attributed variables are also quite difficult to get wrong. These will always contain an integer and dumping them won't change that. Using them later on might be a problem, though.

There are other attributes, like lower- or upper-case-content-only variables (ugh), which, again, are non-problematic at dump time but might behave weird later on if the attributes are stripped.

Associative arrays are special beasts, though. Bash isn't able to determine whether a variable is meant to be an associative or plain array automatically:

```bash
$ _GOMODULE_GOSUM_REVERSE_MAP=([github.com%2Fstretchr%2Fobjx%2F@v%2Fv0.1.0.zip]="github.com/stretchr/objx/@v/v0.1.0.zip")
bash: github.com%2Fstretchr%2Fobjx%2F@v%2Fv0.1.0.zip: syntax error: invalid arithmetic operator (error token is ".com%2Fstretchr%2Fobjx%2F@v%2Fv0.1.0.zip")
$ declare -p _GOMODULE_GOSUM_REVERSE_MAP
declare -a _GOMODULE_GOSUM_REVERSE_MAP=()
$ # See how it interpreted that syntax as a plain array?
```

but (note how the definition is exactly(!) the same, we're just supplying the attribute directly):

```bash
$ unset _GOMODULE_GOSUM_REVERSE_MAP
$ declare -A _GOMODULE_GOSUM_REVERSE_MAP=([github.com%2Fstretchr%2Fobjx%2F@v%2Fv0.1.0.zip]="github.com/stretchr/objx/@v/v0.1.0.zip")
$ # works fine!
```

You could argue that this is actually a bug in bash, but it's pretty moot.

Paludis is currently stripping all attributes implicitly by dumping via the `set` shell builtin, and that's a bug. Portage is not doing that.

**Comment by MageSlayer** [comment]
Ok. Much clearer now, thank you.
So the fix to change variable dump to "declare -p" in those Paludis files, you've mentioned. Right?

**Comment by Ionic** [comment]
In general and very broadly, yes, but it's a lot more complicated than just using `declare -p` for  the reasons I've mentioned. :)

Using `declare` has the side effect of making variables local in functions and since we're sourcing in a function, loading up an `environment.bz2` file created like this will essentially be a no-op. Not exactly what we want.

I've been toying with this three months ago, but didn't finish it and left it stale. I'll get back to it when I have more time. Writing this stuff down actually also gave me a few helpful insights.

**Comment by MageSlayer** [comment]
Can't we assign local variable to a required global variable immediately after "declare -p"?

**Comment by Ionic** [comment]
That was my initial idea. I rewrote everything via `declare -p | sed -e '/^declare -[^-]\+ / s/^declare -/declare -g/' -e '/^declare -- / s/^declare --/declare -g/'`, hence adding a `-g` everywhere, but I think that I shouldn't do that there. Portage isn't doing it.

Instead, it's probably better to add the `-g` flag when loading up the `environment.bz2`.

Don't worry, I'll create a PR once I get this properly running and tests pass.
