### ISSUE TITLE
sys-devel/gcc:8.4.0 fails to build with sys-devel/gcc:9.3.0 (other combinations unknown)

### ISSUE THREAD

**Issue by Ionic** [MageSlayer/paludis-gentoo-patches#27]
I'm unable to build `sys-devel/gcc-8.4.0-r1` with the system compiler set to `sys-devel/gcc-9.3.0-r2`.

It actually completes `src_compile` just fine, but then tries to rebuild a few things in `src_install` (which is also true with portage) and fails:

```
make[2]: Entering directory '/var/tmp/paludis/sys-devel-gcc-8.4.0-r1/work/build/libcc1'
/bin/bash ./libtool --tag=CXX   --mode=compile x86_64-pc-linux-gnu-g++ -std=gnu++98 -DHAVE_CONFIG_H -I. -I/var/tmp/paludis/sys-devel-gcc-8.4.0-r1/work/gcc-8.4.0/libcc1  -I /var/tmp/paludis/sys-devel-gcc-8.4.0-r1/work/gcc-8.4.0/libcc1/../include -I /var/tmp/paludis/sys-devel-gcc-8.4.0-r1/work/gcc-8.4.0/libcc1/../libgcc -I ../gcc -I/var/tmp/paludis/sys-devel-gcc-8.4.0-r1/work/gcc-8.4.0/libcc1/../gcc    -W -Wall  -fvisibility=hidden -march=native -mtune=native -Wall -pipe -g3 -ggdb3 -gdwarf-4 -fno-omit-frame-pointer -O2 -MT findcomp.lo -MD -MP -MF .deps/findcomp.Tpo -c -o findcomp.lo /var/tmp/paludis/sys-devel-gcc-8.4.0-r1/work/gcc-8.4.0/libcc1/findcomp.cc
libtool: compile:  x86_64-pc-linux-gnu-g++ -std=gnu++98 -DHAVE_CONFIG_H -I. -I/var/tmp/paludis/sys-devel-gcc-8.4.0-r1/work/gcc-8.4.0/libcc1 -I /var/tmp/paludis/sys-devel-gcc-8.4.0-r1/work/gcc-8.4.0/libcc1/../include -I /var/tmp/paludis/sys-devel-gcc-8.4.0-r1/work/gcc-8.4.0/libcc1/../libgcc -I ../gcc -I/var/tmp/paludis/sys-devel-gcc-8.4.0-r1/work/gcc-8.4.0/libcc1/../gcc -W -Wall -fvisibility=hidden -march=native -mtune=native -Wall -pipe -g3 -ggdb3 -gdwarf-4 -fno-omit-frame-pointer -O2 -MT findcomp.lo -MD -MP -MF .deps/findcomp.Tpo -c /var/tmp/paludis/sys-devel-gcc-8.4.0-r1/work/gcc-8.4.0/libcc1/findcomp.cc  -fPIC -DPIC -o .libs/findcomp.o
x86_64-pc-linux-gnu-g++: /var/tmp/paludis/sys-devel-gcc-8.4.0-r1/work/build/x86_64-pc-linux-gnu/libstdc++-v3/src/.libs/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by x86_64-pc-linux-gnu-g++)
```

I've ruled out the usual culprits, like binutils plugins, gold and LTO (I personally use neither).

The same build succeeds (same USE flags, same system compiler, same `C(XX)FLAGS` and `LDFLAGS`) just fine with portage, so I guess that something within paludis must trigger the issue.

Nothing in the `toolchain` eclass does `LD_PRELOAD` or `LD_LIBRARY_PATH` magic, as far as I can tell, so I have no idea why this older `libstdc++.so` would be loaded to be used with the system compiler when building this file.

More debugging is necessary here, but I currently don't have the time for that. Writing this up as a bug report for future reference.

**Comment by negril** [comment]
Check the line 239 in the Makefile.in. gcc sets that include directory itself when bootstrapping. No clue what portage does to ignore that.

You might want to look into whether you are able compile older gcc versions with newer gcc in the first place.
Maybe compile it by hand and see if it works?

```
@if target-libstdc++-v3-bootstrap
# Override the above if we're bootstrapping C++.
POSTSTAGE1_CXX_EXPORT = \
  CXX="$(STAGE_CC_WRAPPER) $$r/$(HOST_SUBDIR)/prev-gcc/xg++$(exeext) \
    -B$$r/$(HOST_SUBDIR)/prev-gcc/ -B$(build_tooldir)/bin/ -nostdinc++ \
    -B$$r/prev-$(TARGET_SUBDIR)/libstdc++-v3/src/.libs \
    -B$$r/prev-$(TARGET_SUBDIR)/libstdc++-v3/libsupc++/.libs \
    `if $(LEAN); then echo ' -isystem '; else echo ' -I'; fi`$$r/prev-$(TARGET_SUBDIR)/libstdc++-v3/include/$(TARGET_SUBDIR) \
    `if $(LEAN); then echo ' -isystem '; else echo ' -I'; fi`$$r/prev-$(TARGET_SUBDIR)/libstdc++-v3/include \
    `if $(LEAN); then echo ' -isystem '; else echo ' -I'; fi`$$s/libstdc++-v3/libsupc++ \
    -L$$r/prev-$(TARGET_SUBDIR)/libstdc++-v3/src/.libs \
    -L$$r/prev-$(TARGET_SUBDIR)/libstdc++-v3/libsupc++/.libs"; \
    export CXX; \
  CXX_FOR_BUILD="$$CXX"; export CXX_FOR_BUILD;
@endif target-libstdc++-v3-bootstrap
```


PS. it's been a while since those days in #linux.de on qnet ;)

**Comment by Ionic** [comment]
I think that we tracked that down to ccache.

I'll rebuild the package both with portage (that hasn't been using ccache so far because I've been too lazy to configure it) and paludis, the latter with ccache disabled.

The 4.x series of ccache seems to link against libstdc++ nowadays, which the 3.x series didn't. Since 4.x is rather new, it explains the recent build failures.

**Comment by Ionic** [comment]
Yep, it is:

  - paludis w/ ccache: fails
  - paludis w/o ccache: suceeds
  - portage w/ ccache: fails
  - portage w/o ccache: succeeds

No paludis bug.

Tracked at https://bugs.gentoo.org/761220. Closing here.

**Comment by MageSlayer** [comment]
Thanks for the investigation.
