### ISSUE TITLE
new llvm.org eclass breaks unpack in paludis on llvm related packages

### ISSUE THREAD

**Issue by hlandgarten** [MageSlayer/paludis-gentoo-patches#30]
this is error when running cave resolve llvm -1zx:

 * Unpacking from llvmorg-12.0.0.tar.gz ...                                                                                                                        [ ok ]
>>> Unpacking llvm-12.0.0-manpages.tar.bz2 to /var/tmp/paludis/sys-devel-llvm-12.0.0/work
tar jxf /usr/portage/distfiles/llvm-12.0.0-manpages.tar.bz2 --no-same-owner
>>> Unpacking llvm-gentoo-patchset-12.0.0-1.tar.xz to /var/tmp/paludis/sys-devel-llvm-12.0.0/work
xz -dc /usr/portage/distfiles/llvm-gentoo-patchset-12.0.0-1.tar.xz | strip_tar_corruption | tar xf - --no-same-owner

Error:
  * In program cave perform install --hooks --managed-output --output-exclusivity with-others =sys-devel/llvm-12.0.0:12::gentoo --destination installed --replacing =sys-devel/llvm-12.0.0:12::installed --x-of-y 1 of 1:
  * When installing 'sys-devel/llvm-12.0.0:12::gentoo' replacing { 'sys-devel/llvm-12.0.0:12::installed' }:
  * When running an ebuild command on 'sys-devel/llvm-12.0.0:12::gentoo':
  * Install failed for 'sys-devel/llvm-12.0.0:12::gentoo' (paludis::ActionFailedError)

!!! ERROR in sys-devel/llvm-12.0.0::gentoo:
!!! In llvm.org_src_unpack at line 3706
!!! 0|0 

!!! Call stack:
!!!    * llvm.org_src_unpack (/var/tmp/paludis/sys-devel-llvm-12.0.0/temp/loadsaveenv:3706)
!!!    * src_unpack (/var/tmp/paludis/sys-devel-llvm-12.0.0/temp/loadsaveenv:5309)
!!!    * ebuild_f_unpack (/usr/libexec/paludis/2/src_unpack.bash:47)
!!!    * ebuild_main (/usr/libexec/paludis/ebuild.bash:675)
!!!    * main (/usr/libexec/paludis/ebuild.bash:698)

diefunc: making ebuild PID 1639911 exit with error
die trap: exiting with error.

Unpack fails on the following code in loadsaveenv in temp:
    if [[ -n ${LLVM_PATCHSET} ]]; then
        local IFS='|';
        grep -E -r -L "^Gentoo-Component:.*(${components[*]})" "${WORKDIR}/llvm-gentoo-patchset-${LLVM_PATCHSET}" | xargs rm;
        _paludis_pipestatus="${PIPESTATUS[*]}";
        [[ -z "${_paludis_pipestatus//[ 0]/}" ]] || diefunc "${FUNCNAME:-$0}" "$LINENO";
    fi

**Comment by Ionic** [comment]
Yes, it does.

paludis' defines `assert` as an alias, which is essentially inlined into the calling function (and which generally makes sense, since it will be executed in the calling function context).

Unfortunately, this function changes `IFS`, but the alias depends upon a specific `IFS` value (the default one, although `IFS=' '` would also work correctly).

We should be easily able to fix that by temporarily resetting `IFS` to the default vlaue.
