### ISSUE TITLE
paludis will not build with boost-1.78

### ISSUE THREAD

**Issue by hlandgarten** [MageSlayer/paludis-gentoo-patches#35]
ake[2]: *** No rule to make target '/usr/lib64/libboost_python39.so.1.78.0', needed by 'python/libpaludispython_3.0.so.300.0.0'.  Stop.

**Comment by thesamesam** [comment]
This is https://bugs.gentoo.org/829031.

**Comment by hlandgarten** [comment]
resolved by boost-1.78.0-r1
